# This workflow will run tests using node and then publish a package to NPM and GitHub Packages when a release is created

name: Build and Publish to NPM

on:
  release:
    types: [created]
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 11.x, 12.x, 13.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMJS_TOKEN}}
      - run: npx pkg . -t node14-linux-x64 -o bin/reshift-security-scan
      - run: npx pkg . -t node14-macos-x64 -o bin/reshift-security-scan-macos
      - run: npx pkg . -t node14-win-x64 -o bin/reshift-security-scan-win.exe
      - uses: actions/upload-artifact@v2
        with:
          name: cli-binaries
          path: bin/reshift-security-scan*
